version: '3.4'

services:
  architecture.presentation:
    image: ${DOCKER_REGISTRY-}architecturepresentation
    build:
      context: .
      dockerfile: Architecture.Presentation/Dockerfile
    depends_on:
      - db
      - redis

  db:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - c:/data/mongo:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - c:/data/redis:/data/redis
