version: '3.4'

services:
  architecture.presentation:
    image: ${DOCKER_REGISTRY-}architecturepresentation
    build:
      context: .
      dockerfile: Architecture.Presentation/Dockerfile
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017-27019:27017-27019"
    volumes:
      - c:/data/mongo:/data/mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - c:/data/redis:/data/redis

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    depends_on:
      - mongo
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_OPTIONS_EDITORTHEME: panda-syntax
      ME_CONFIG_EDITORTHEME: panda-syntax
